<a href="https://colab.research.google.com/github/jeniferGoncalvesDaSilvaDev/Estatistica-python/blob/main/poisson_dist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from scipy.stats import poisson,binom,bernoulli
import numpy as np

In [ ]:
#gerando amostras aleatorias com bernoulli
p = 0.5
a = bernoulli.rvs(p,size=10)
print(a)

[0 1 1 0 0 0 1 1 0 0]


In [ ]:

#gerando amostras aleatorias com numpy
a = np.random.poisson(k,size = 10)
print(a)
k = 10
#gerando amostras aleatorias com scipy
amostras = poisson.rvs(k, size=10)
print(amostras)

[11 14  9 14  8  9 12  9 10  5]
[15  8  6  9  9  7 17  5  7  5]


In [ ]:
#amostras aleatorias com binomal
k = 5
p =0.5
t = 10
a = np.random.binomial(t,p,size=10)
print(a)
a2 = binom.rvs(t,p,size=10)
print(a2)

[6 5 4 5 4 7 6 5 5 5]
[4 3 6 3 5 7 4 4 6 4]


In [21]:
#encontrar 6 pacientes doentes em 3 dia
# numero de eventos
k = 6
# intervalo de tempo
t = 3
p_poissom = poisson.pmf(k,t)*100
print(f'{p_poissom:.2f}')
media = poisson.mean(t)
variancia = poisson.var(t)
print(media,variancia)

5.04
3.0 3.0


In [20]:
k =[5,9,2,4]
t = 10
p_poissom = poisson.pmf(k,t)*100
print(p_poissom)
media = poisson.mean(t)
variancia = poisson.var(t)
print(media,variancia)

[ 3.78332748 12.51100357  0.22699965  1.89166374]
10.0 10.0


In [ ]:
k = np.arange(1,6)
t = np.arange(1,6)
p_poisson = poisson.pmf(k,t)*100
print(p_poisson)

[36.78794412 27.06705665 22.40418077 19.53668148 17.54673698]
